### ISSUE TITLE
Unhandled Promise rejection (lines are because I formatted it with a lua beautifier, same thing happens with the regular code)

### ISSUE THREAD

**Issue by 0x2640** [richie0866/MidiPlayer#12]
(10:23:02 PM) Unhandled Promise rejection:

-- Promise.Error(ExecutionError) --
Components is not a valid member of LocalScript "Tree.MidiPlayer"
@src/init.client.lua (Tree.MidiPlayer):5
JxPQZXc87BmR14:575 function runExecutor
JxPQZXc87BmR14:586
JxPQZXc87BmR14:1438 function cW
JxPQZXc87BmR14:1526

Promise created at:

JxPQZXc87BmR14:584 function deferExecutor
JxPQZXc87BmR14:416 function simulate
JxPQZXc87BmR14:249 function start
JxPQZXc87BmR14:3487
JxPQZXc87BmR14:1438 function cW
JxPQZXc87BmR14:1442

JxPQZXc87BmR14:1918 function timeout
JxPQZXc87BmR14:420 function simulate
JxPQZXc87BmR14:249 function start
JxPQZXc87BmR14:3487
JxPQZXc87BmR14:1438 function cW
JxPQZXc87BmR14:1442

**Comment by 0x2640** [comment]
This happened using Synapse X 3.0, and it seems to work with no issues on Synapse X

**Comment by richie0866** [comment]
See issue #11 and let me know what the code there outputs 🙌🏿 I can't reproduce this issue and need to troubleshoot

**Comment by 0x2640** [comment]
Will do once 3.0 updates.
